application: example-application
version: ebs
runtime: python
api_version: 1

default_expiration: 7d

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: never

- url: /s
  static_dir: static
  secure: never
  expiration: 7d

- url: /settings.*
  script: api_settings.py
  login: admin

- url: /.*
  script: application.py

